### ISSUE TITLE
Bro I have one issue in library that you have given.

### ISSUE THREAD

**Issue by Rutu83** [1902shubh/InstaStory#7]
<img width="755" alt="image" src="https://user-images.githubusercontent.com/52393147/200787170-395897be-e822-4020-bbf0-e8fb2c301e17.png">
here is the image of the error I think you have to replace from this **"com.github.florent37:shapeofview:1.3.2"** to new one this :  implementation 'io.github.florent37:shapeofview:1.4.7' into the library because the old one is causing build problems.

**Comment by 1902shubh** [comment]
replace com with io

**Comment by 1902shubh** [comment]
replace it with io.gtihub
